#!/groovy


def APP = params.APP
def PROJECT = params.PROJECT

def CONTAINER_NAME = "${PROJECT}/${APP}:v$env.BUILD_NUMBER"


/* AWS Docker spot instance */
pipeline {

    agent {
        label 'ec2'
    }

    stages {
        /* Checkout code */
        stage("Checkout and Build") {

            steps {
              retry(2) {
                checkout scm
              }

              dir("app") {
                writeFile file: "version.json", text: """
                {
                "buildNumber": "${env.BUILD_NUMBER}",
                "buildTag": "${env.BUILD_TAG}",
                "buildTime": "${env.BUILD_TIMESTAMP}"
                }
                """

                withCredentials([string(credentialsId: 'docker-login-srhopkins', variable: 'DOCKER_LOGIN')]) {
                    sh "${DOCKER_LOGIN}"
                    sh "docker build -t ${CONTAINER_NAME} ."
                    sh "docker push ${CONTAINER_NAME}"
                }
              }
            }
            // post {
            //   success {
            //     slackSend color: 'good', message: "${APP}, image: ${env.BUILD_NUMBER} has been built successfully"
            //   }
            // }
        }


        /* send to kubectl deploy job with dev params */
        stage('Deploy to INT') {
          steps {
            build job: 'example-project-deploy',
            parameters: [
                string(name: 'IMAGE', value: "${CONTAINER_NAME}"),
                string(name: 'NAMESPACE', value: "int"),
                string(name: 'DEPLOYMENT', value: "${APP}")
            ]
          }
        //   post {
        //     success {
        //       slackSend color: 'good', message: "${APP}, image : ${env.BUILD_NUMBER}_master deployed to INT"
        //     }
        //   }
        }

        /* push to STG env */
        stage('Gate to STG') {

            steps {
                timeout(time: 7, unit: 'DAYS') {
                    input (
                        message: 'Do you want to push to STG?', submitterParameter: 'APPROVED_BY'
                    )
                }
            }
        }

        /* send to kubectl deploy job with stg params */
        stage('Deploy to stg') {
            steps {
                build job: 'example-project-deploy',
                parameters: [
                    string(name: 'IMAGE', value: "${CONTAINER_NAME}"),
                    string(name: 'NAMESPACE', value: "stg"),
                    string(name: 'DEPLOYMENT', value: "${APP}")
                ]
            }
            // post {
            //   success {
            //     slackSend color: 'good', message: "${APP}, image : ${env.BUILD_NUMBER}_master deployed to STG"
            //   }
            // }
        }

        /* push to PRD env */
        stage('Gate to PRD') {

            steps {
                timeout(time: 7, unit: 'DAYS') {
                    input (
                        message: 'Do you want to push to PRD?', submitterParameter: 'APPROVED_BY'
                    )
                }
            }
        }

        /* send to kubectl deploy job with prd params */
        stage('Deploy to prd') {
            steps {
                build job: 'example-project-deploy',
                parameters: [
                    string(name: 'IMAGE', value: "${CONTAINER_NAME}"),
                    string(name: 'NAMESPACE', value: "prd"),
                    string(name: 'DEPLOYMENT', value: "${APP}")
                ]
            }
            // post {
            //   success {
            //     slackSend color: 'good', message: "${APP}, image : ${env.BUILD_NUMBER}_master deployed to PRD"
            //   }
            // }
        }
    }
    post {
      failure {
        slackSend color: 'bad', message: "${APP} job failed - ${BUILD_URL}"
      }
    }
}