controller:
  config:
    use-proxy-protocol: "true"

  replicaCount: 3

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  
  stats:
    enabled: true

rbac:
  create: false

